"""Initial migration

Revision ID: 63edfa96857d
Revises: 
Create Date: 2024-12-04 16:22:30.067876

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63edfa96857d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demographics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('UrbanizatonRate', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.alter_column('StateID',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('demographics_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'states', ['StateID'], ['id'])
        batch_op.drop_column('UrbanizationRate')

    with op.batch_alter_table('diversity', schema=None) as batch_op:
        batch_op.alter_column('StateID',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('diversity_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'states', ['StateID'], ['id'])

    with op.batch_alter_table('economy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('MajorINdustries', mysql.JSON(), nullable=True))
        batch_op.alter_column('StateID',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('economy_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'states', ['StateID'], ['id'])
        batch_op.drop_column('MajorIndustries')

    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_column('StateID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('StateID', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('economy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('MajorIndustries', mysql.JSON(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('economy_ibfk_1', 'states', ['StateID'], ['StateID'])
        batch_op.alter_column('StateID',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('MajorINdustries')

    with op.batch_alter_table('diversity', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('diversity_ibfk_1', 'states', ['StateID'], ['StateID'])
        batch_op.alter_column('StateID',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('demographics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('UrbanizationRate', mysql.DECIMAL(precision=5, scale=2), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('demographics_ibfk_1', 'states', ['StateID'], ['StateID'])
        batch_op.alter_column('StateID',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('UrbanizatonRate')

    # ### end Alembic commands ###
