"""updated states id name

Revision ID: cfaf07487525
Revises: 63edfa96857d
Create Date: 2024-12-04 17:00:30.436918

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cfaf07487525'
down_revision = '63edfa96857d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demographics', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'states', ['StateID'], ['StateID'])
        batch_op.drop_column('UrbanizationRate')

    with op.batch_alter_table('diversity', schema=None) as batch_op:
        batch_op.alter_column('StateID',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('economy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('MajorINdustries', mysql.JSON(), nullable=True))
        batch_op.alter_column('StateID',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('MajorIndustries')

    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'regions', ['RegionID'], ['RegionID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('economy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('MajorIndustries', mysql.JSON(), nullable=True))
        batch_op.alter_column('StateID',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('MajorINdustries')

    with op.batch_alter_table('diversity', schema=None) as batch_op:
        batch_op.alter_column('StateID',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('demographics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('UrbanizationRate', mysql.DECIMAL(precision=5, scale=2), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
