"""updated states id name

Revision ID: f0f465dcde29
Revises: cfaf07487525
Create Date: 2024-12-04 17:02:22.243424

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0f465dcde29'
down_revision = 'cfaf07487525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('economy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('MajorINdustries', mysql.JSON(), nullable=True))
        batch_op.alter_column('StateID',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('MajorIndustries')

    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'regions', ['RegionID'], ['RegionID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('economy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('MajorIndustries', mysql.JSON(), nullable=True))
        batch_op.alter_column('StateID',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('MajorINdustries')

    # ### end Alembic commands ###
